### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by thynson** [asvetliakov/Huject#6]
Stacktrace is

```
                        throw new Error(`Unknown definition: ${paramDefinition.toString()}`)
                                                                              ^
TypeError: Cannot read property 'toString' of undefined

    at ContainerResolver.resolveProperties (/Users/lanxingcan/Documents/Workspace/fittime-notification-worker/node_modules/huject/src/resolver.ts:161:79)
    at ContainerResolver.resolve (/Users/lanxingcan/Documents/Workspace/fittime-notification-worker/node_modules/huject/src/resolver.ts:104:30)
    at Container.resolve (/Users/lanxingcan/Documents/Workspace/fittime-notification-worker/node_modules/huject/src/container.ts:111:30)
    at Object.<anonymous> (/Users/lanxingcan/Documents/Workspace/fittime-notification-worker/index.ts:20:8)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/ts-node/src/index.ts:290:14)
    at Object.require.extensions.(anonymous function) [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:307:14)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Function.Module.runMain (module.js:590:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/ts-node/src/_bin.ts:179:12)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)

```

**Comment by Smert** [comment]
@thynson 

tsconfig.json
```
"emitDecoratorMetadata": true
```
